import dgram from "node:dgram";

function cstring(data:Buffer,offset:number){const end=data.indexOf(0,offset);if(end<0)throw new Error("A2S string is unterminated");return {value:data.toString("utf8",offset,end),next:end+1}}
export type A2sInfo={name:string;map:string;folder:string;game:string;players:number;maxPlayers:number;bots:number;password:boolean;vac:boolean;version:string};
export function parseA2sInfo(data:Buffer):A2sInfo{if(data.length<6||data.readInt32LE(0)!==-1||data[4]!==0x49)throw new Error("Not an A2S_INFO response");let o=6;const name=cstring(data,o);o=name.next;const map=cstring(data,o);o=map.next;const folder=cstring(data,o);o=folder.next;const game=cstring(data,o);o=game.next;if(o+8>data.length)throw new Error("A2S_INFO response is truncated");o+=2;const players=data[o++],maxPlayers=data[o++],bots=data[o++];o+=2;const password=Boolean(data[o++]),vac=Boolean(data[o++]);const version=cstring(data,o).value;return{name:name.value,map:map.value,folder:folder.value,game:game.value,players,maxPlayers,bots,password,vac,version}}
const request=(challenge?:Buffer)=>Buffer.concat([Buffer.from([255,255,255,255,0x54]),Buffer.from("Source Engine Query\0"),...(challenge?[challenge]:[])]);
export async function queryA2sInfo(host:string,port:number,timeoutMs=1500){return new Promise<A2sInfo>((resolve,reject)=>{const socket=dgram.createSocket("udp4");let timer:NodeJS.Timeout;let challenged=false;const finish=(error?:Error,info?:A2sInfo)=>{clearTimeout(timer);socket.close();error?reject(error):resolve(info!)};timer=setTimeout(()=>finish(new Error("A2S query timed out")),timeoutMs);socket.on("error",error=>finish(error));socket.on("message",data=>{try{if(data.length>=9&&data.readInt32LE(0)===-1&&data[4]===0x41&&!challenged){challenged=true;socket.send(request(data.subarray(5,9)),port,host);return}finish(undefined,parseA2sInfo(data))}catch(error){finish(error instanceof Error?error:new Error(String(error)))}});socket.send(request(),port,host)})}

import net from "node:net";
function encodeVarInt(value:number){const out:number[]=[];do{let byte=value&127;value>>>=7;if(value)byte|=128;out.push(byte)}while(value);return Buffer.from(out)}
function decodeVarInt(data:Buffer,offset=0){let value=0,position=0;for(let i=offset;i<data.length&&position<35;i++){const byte=data[i];value|=(byte&127)<<position;if((byte&128)===0)return{value,next:i+1};position+=7}return null}
export type MinecraftStatus={version:string;protocol:number;motd:string;players:number;maxPlayers:number;samplePlayers:string[];latencyMs:number};
export function parseMinecraftStatus(value:unknown,latencyMs=0):MinecraftStatus{const root=value as {version?:{name?:unknown;protocol?:unknown};description?:unknown;players?:{online?:unknown;max?:unknown;sample?:{name?:unknown}[]}};const description=typeof root.description==="string"?root.description:root.description&&typeof root.description==="object"&&"text" in root.description?String((root.description as {text:unknown}).text??""):"";return{version:String(root.version?.name??"unknown"),protocol:Number(root.version?.protocol??0),motd:description,players:Number(root.players?.online??0),maxPlayers:Number(root.players?.max??0),samplePlayers:Array.isArray(root.players?.sample)?root.players.sample.map(player=>String(player.name??"")).filter(Boolean).slice(0,100):[],latencyMs}}
export async function queryMinecraftStatus(host:string,port:number,timeoutMs=1500){return new Promise<MinecraftStatus>((resolve,reject)=>{const started=Date.now(),socket=net.createConnection({host,port});let data=Buffer.alloc(0),settled=false;const finish=(error?:Error,status?:MinecraftStatus)=>{if(settled)return;settled=true;socket.destroy();error?reject(error):resolve(status!)};socket.setTimeout(timeoutMs);socket.once("timeout",()=>finish(new Error("Minecraft status timed out")));socket.once("error",finish);socket.once("connect",()=>{const address=Buffer.from(host);const body=Buffer.concat([encodeVarInt(0),encodeVarInt(0),encodeVarInt(address.length),address,Buffer.from([port>>8,port&255]),encodeVarInt(1)]);socket.write(Buffer.concat([encodeVarInt(body.length),body,Buffer.from([1,0])]))});socket.on("data",chunk=>{try{data=Buffer.concat([data,chunk]);const packet=decodeVarInt(data);if(!packet||data.length<packet.next+packet.value)return;const id=decodeVarInt(data,packet.next);if(!id||id.value!==0)throw new Error("Unexpected Minecraft status packet");const length=decodeVarInt(data,id.next);if(!length||data.length<length.next+length.value)return;const json=JSON.parse(data.toString("utf8",length.next,length.next+length.value));finish(undefined,parseMinecraftStatus(json,Date.now()-started))}catch(error){finish(error instanceof Error?error:new Error(String(error)))}})})}

export type A2sPlayer={index:number;name:string;score:number;durationSeconds:number};
export function parseA2sPlayers(data:Buffer):A2sPlayer[]{if(data.length<6||data.readInt32LE(0)!==-1||data[4]!==0x44)throw new Error("Not an A2S_PLAYER response");const count=data[5];let offset=6;const players:A2sPlayer[]=[];for(let i=0;i<count;i++){if(offset>=data.length)throw new Error("A2S_PLAYER response is truncated");const index=data[offset++],name=cstring(data,offset);offset=name.next;if(offset+8>data.length)throw new Error("A2S_PLAYER response is truncated");const score=data.readInt32LE(offset);offset+=4;const durationSeconds=data.readFloatLE(offset);offset+=4;players.push({index,name:name.value,score,durationSeconds})}return players}
export async function queryA2sPlayers(host:string,port:number,timeoutMs=1500){return new Promise<A2sPlayer[]>((resolve,reject)=>{const socket=dgram.createSocket("udp4");let timer:NodeJS.Timeout,challenged=false,settled=false;const finish=(error?:Error,players?:A2sPlayer[])=>{if(settled)return;settled=true;clearTimeout(timer);socket.close();error?reject(error):resolve(players!)};timer=setTimeout(()=>finish(new Error("A2S player query timed out")),timeoutMs);socket.on("error",error=>finish(error));socket.on("message",data=>{try{if(data.length>=9&&data.readInt32LE(0)===-1&&data[4]===0x41&&!challenged){challenged=true;socket.send(Buffer.concat([Buffer.from([255,255,255,255,0x55]),data.subarray(5,9)]),port,host);return}finish(undefined,parseA2sPlayers(data))}catch(error){finish(error instanceof Error?error:new Error(String(error)))}});socket.send(Buffer.from([255,255,255,255,0x55,255,255,255,255]),port,host)})}
