export type InstallerKind = "mojang" | "fabric" | "bedrock" | "steamcmd" | "hytale" | "manual";

export type GameDef = {
  id: string;
  name: string;
  short: string;
  tagline: string;
  art: string;
  accent: string;
  accentSoft: string;
  defaultPort: number;
  queryPort?: number;
  protocol: "TCP" | "UDP";
  defaultMemory: number;
  minMemory: number;
  maxMemory: number;
  defaultMaxPlayers: number;
  maxPlayersCap: number;
  versions: string[];
  loaders?: { id: string; label: string }[];
  modSource?: string;
  supportsMods: boolean;
  difficulty: boolean;
  worldLabel: string;
  installSizeMb: number;
  installer: InstallerKind;
  installerLabel: string;
  steamAppId?: number;
  requiresPassword?: boolean;
};

/**
 * Supported installation recipes. "manual" games are still fully manageable,
 * but Server Hub will not invent a download URL: the user supplies a command
 * and (optionally) an existing working directory.
 */
export const GAMES: GameDef[] = [
  {
    id: "minecraft",
    name: "Minecraft: Java Edition",
    short: "Minecraft",
    tagline: "Official Mojang dedicated server, downloaded and verified locally.",
    art: "",
    accent: "#2fae62",
    accentSoft: "rgba(47,174,98,0.12)",
    defaultPort: 25565,
    protocol: "TCP",
    defaultMemory: 4096,
    minMemory: 1024,
    maxMemory: 32768,
    defaultMaxPlayers: 20,
    maxPlayersCap: 500,
    versions: ["1.21.4", "1.21.1", "1.20.6", "1.20.1", "1.19.4", "1.18.2", "1.16.5"],
    supportsMods: false,
    difficulty: true,
    worldLabel: "World name",
    installSizeMb: 80,
    installer: "mojang",
    installerLabel: "Official Mojang download",
  },
  {
    id: "minecraft-modded",
    name: "Minecraft: Fabric",
    short: "MC Fabric",
    tagline: "A real Fabric server with live Modrinth search and downloads.",
    art: "",
    accent: "#9a5cf0",
    accentSoft: "rgba(154,92,240,0.12)",
    defaultPort: 25565,
    protocol: "TCP",
    defaultMemory: 8192,
    minMemory: 2048,
    maxMemory: 49152,
    defaultMaxPlayers: 20,
    maxPlayersCap: 200,
    versions: ["1.21.4", "1.21.1", "1.20.1", "1.19.2", "1.18.2", "1.16.5"],
    loaders: [{ id: "fabric", label: "Fabric (latest stable loader)" }],
    modSource: "Modrinth",
    supportsMods: true,
    difficulty: true,
    worldLabel: "World name",
    installSizeMb: 160,
    installer: "fabric",
    installerLabel: "Fabric Meta + Mojang",
  },
  {
    id: "minecraft-bedrock",
    name: "Minecraft: Bedrock",
    short: "MC Bedrock",
    tagline: "Official Bedrock dedicated server for Windows or Linux.",
    art: "",
    accent: "#1f9fd6",
    accentSoft: "rgba(31,159,214,0.12)",
    defaultPort: 19132,
    protocol: "UDP",
    defaultMemory: 2048,
    minMemory: 512,
    maxMemory: 16384,
    defaultMaxPlayers: 10,
    maxPlayersCap: 100,
    versions: ["latest"],
    supportsMods: false,
    difficulty: true,
    worldLabel: "World name",
    installSizeMb: 150,
    installer: "bedrock",
    installerLabel: "Official Minecraft download",
  },
  {
    id: "valheim",
    name: "Valheim",
    short: "Valheim",
    tagline: "Installed and updated with SteamCMD's anonymous dedicated-server depot.",
    art: "",
    accent: "#d79320",
    accentSoft: "rgba(215,147,32,0.12)",
    defaultPort: 2456,
    queryPort: 2457,
    protocol: "UDP",
    defaultMemory: 4096,
    minMemory: 2048,
    maxMemory: 16384,
    defaultMaxPlayers: 10,
    maxPlayersCap: 64,
    versions: ["latest"],
    supportsMods: false,
    difficulty: false,
    worldLabel: "World name",
    installSizeMb: 1800,
    installer: "steamcmd",
    installerLabel: "SteamCMD app 896660",
    steamAppId: 896660,
    requiresPassword: true,
  },
  {
    id: "ark",
    name: "ARK: Survival Evolved",
    short: "ARK: SE",
    tagline: "The official ARK dedicated server, installed through SteamCMD.",
    art: "",
    accent: "#f06a2e",
    accentSoft: "rgba(240,106,46,0.12)",
    defaultPort: 7777,
    queryPort: 27015,
    protocol: "UDP",
    defaultMemory: 12288,
    minMemory: 6144,
    maxMemory: 65536,
    defaultMaxPlayers: 32,
    maxPlayersCap: 200,
    versions: ["latest"],
    supportsMods: false,
    difficulty: true,
    worldLabel: "Map name",
    installSizeMb: 42000,
    installer: "steamcmd",
    installerLabel: "SteamCMD app 376030",
    steamAppId: 376030,
  },
  {
    id: "terraria",
    name: "Terraria",
    short: "Terraria",
    tagline: "Official Terraria server files installed through SteamCMD.",
    art: "",
    accent: "#10b5a0",
    accentSoft: "rgba(16,181,160,0.12)",
    defaultPort: 7777,
    protocol: "TCP",
    defaultMemory: 2048,
    minMemory: 512,
    maxMemory: 8192,
    defaultMaxPlayers: 16,
    maxPlayersCap: 255,
    versions: ["latest"],
    supportsMods: false,
    difficulty: true,
    worldLabel: "World name",
    installSizeMb: 700,
    installer: "steamcmd",
    installerLabel: "SteamCMD app 105600",
    steamAppId: 105600,
  },
  {
    id: "rust",
    name: "Rust",
    short: "Rust",
    tagline: "Official Rust Dedicated server installed and validated with SteamCMD.",
    art: "",
    accent: "#c4763c",
    accentSoft: "rgba(196,118,60,0.12)",
    defaultPort: 28015,
    queryPort: 28016,
    protocol: "UDP",
    defaultMemory: 12288,
    minMemory: 8192,
    maxMemory: 65536,
    defaultMaxPlayers: 100,
    maxPlayersCap: 500,
    versions: ["latest"],
    supportsMods: false,
    difficulty: false,
    worldLabel: "Identity / map name",
    installSizeMb: 26000,
    installer: "steamcmd",
    installerLabel: "SteamCMD app 258550",
    steamAppId: 258550,
  },
  {
    id: "dragonwilds",
    name: "RuneScape: Dragonwilds",
    short: "Dragonwilds",
    tagline: "Official dedicated server installed anonymously through SteamCMD.",
    art: "",
    accent: "#e63f6d",
    accentSoft: "rgba(230,63,109,0.12)",
    defaultPort: 7777,
    protocol: "UDP",
    defaultMemory: 8192,
    minMemory: 4096,
    maxMemory: 32768,
    defaultMaxPlayers: 8,
    maxPlayersCap: 32,
    versions: ["latest"],
    supportsMods: false,
    difficulty: false,
    worldLabel: "Realm name",
    installSizeMb: 20000,
    installer: "steamcmd",
    installerLabel: "SteamCMD app 4019830",
    steamAppId: 4019830,
  },
  {
    id: "hytale",
    name: "Hytale",
    short: "Hytale",
    tagline: "Official downloader with in-console OAuth authorization and a private Java 25 runtime.",
    art: "",
    accent: "#17b2cf",
    accentSoft: "rgba(23,178,207,0.12)",
    defaultPort: 5520,
    protocol: "UDP",
    defaultMemory: 6144,
    minMemory: 4096,
    maxMemory: 32768,
    defaultMaxPlayers: 40,
    maxPlayersCap: 500,
    versions: ["latest"],
    supportsMods: false,
    difficulty: true,
    worldLabel: "Universe name",
    installSizeMb: 30000,
    installer: "hytale",
    installerLabel: "Official Hytale Downloader",
  },
  {
    id: "custom",
    name: "Custom dedicated server",
    short: "Custom",
    tagline: "Run any executable or script from an existing folder, with live stdin and logs.",
    art: "",
    accent: "#8b7aa8",
    accentSoft: "rgba(139,122,168,0.12)",
    defaultPort: 27015,
    protocol: "UDP",
    defaultMemory: 4096,
    minMemory: 512,
    maxMemory: 65536,
    defaultMaxPlayers: 24,
    maxPlayersCap: 500,
    versions: ["manual"],
    supportsMods: false,
    difficulty: false,
    worldLabel: "World / map name",
    installSizeMb: 0,
    installer: "manual",
    installerLabel: "Existing installation / custom command",
  },
];

export function getGame(id: string): GameDef {
  return GAMES.find((g) => g.id === id) ?? GAMES[GAMES.length - 1];
}

export function hasGame(id: string): boolean {
  return GAMES.some((g) => g.id === id);
}
