import assert from "node:assert/strict";
import fs from "node:fs";
import { hostPlatform } from "../src/lib/host-platform";
const before=process.env.SERVERHUB_TARGET_PLATFORM;
process.env.SERVERHUB_TARGET_PLATFORM="win32";assert.equal(hostPlatform(),"win32");
process.env.SERVERHUB_TARGET_PLATFORM="linux";assert.equal(hostPlatform(),"linux");
process.env.SERVERHUB_TARGET_PLATFORM="forged";assert.equal(hostPlatform(),process.platform);
if(before===undefined)delete process.env.SERVERHUB_TARGET_PLATFORM;else process.env.SERVERHUB_TARGET_PLATFORM=before;
const launcher=fs.readFileSync("scripts/portable-launcher.cjs","utf8");assert.ok(launcher.includes('SERVERHUB_TARGET_PLATFORM = "win32"'));
for(const file of ["src/lib/runtime.ts","src/app/api/tools/route.ts","src/app/api/tools/[id]/repair/route.ts","src/lib/windows-authenticode.ts"])assert.ok(!fs.readFileSync(file,"utf8").includes("process.platform"),file);
console.log("CROSS_COMPILED_PLATFORM_REGRESSION_OK");
